In [113]:
import pandas as pd
import numpy as np
import sklearn
from sklearn.neighbors import KNeighborsClassifier as knn


In [114]:
df=pd.read_csv("knn.csv")

In [115]:
df.size

18

In [116]:
df.shape

(6, 3)

In [117]:
df.head()

X  Y Class
0  2  4     N
1  4  6     N
2  4  4     P
3  4  2     N
4  6  4     N

In [118]:
x=df.iloc[:,:-1].values
y=df.iloc[:,2].values

In [119]:
x

array([[2, 4],
       [4, 6],
       [4, 4],
       [4, 2],
       [6, 4],
       [6, 2]])

In [120]:
y

array(['N', 'N', 'P', 'N', 'N', 'P'], dtype=object)

In [121]:
classifier=knn(n_neighbors=3)
#odd no, sqr root of training samples to avoid tie

In [122]:
classifier.fit(x,y) #training data

KNeighborsClassifier(n_neighbors=3)

In [123]:
x_test=np.array([7,6])
y_predict=classifier.predict([x_test]) #predicting using model

In [124]:
y_predict

array(['N'], dtype=object)

In [125]:
from sklearn.neighbors import KNeighborsRegressor as knn1
df=pd.read_csv("knn1.csv")

In [126]:
df

Height  Age  Weight
0    5.00   45      77
1    5.11   26      47
2    5.60   30      55
3    5.90   34      59
4    4.80   40      72
5    5.80   36      60
6    5.30   19      40
7    5.80   28      60
8    5.50   23      45
9    5.60   32      58

In [127]:
x=df.iloc[:,:-1].values
y=df.iloc[:,2].values

In [128]:
x

array([[ 5.  , 45.  ],
       [ 5.11, 26.  ],
       [ 5.6 , 30.  ],
       [ 5.9 , 34.  ],
       [ 4.8 , 40.  ],
       [ 5.8 , 36.  ],
       [ 5.3 , 19.  ],
       [ 5.8 , 28.  ],
       [ 5.5 , 23.  ],
       [ 5.6 , 32.  ]])

In [129]:
y

array([77, 47, 55, 59, 72, 60, 40, 60, 45, 58])

In [130]:
classifier=knn1(n_neighbors=4)
#odd no, sqr root of training samples to avoid tie

In [131]:
classifier.fit(x,y) #training data

KNeighborsRegressor(n_neighbors=4)

In [132]:
x_test=np.array([5.5,26])
y_predict=classifier.predict([x_test]) #predicting using model

In [133]:
y_predict

array([51.75])